/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (ace-combat-3-electrosphere-usa-)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x801761F8u
#define func_801761F8 BootEntry  /* alias */
